### PR TITLE
fix: add promise resolution to fix Promise.allSettled unavailable on mobile

### PR DESCRIPTION
**Pull request by limichange**
## 
## Summary by CodeRabbit

* **Chores**
  * Added and pinned a Promise polyfill to ensure Promise.allSettled support and more consistent behavior across older environments.
* **New Features**
  * Improved calculator logic with additional computation capabilities and updated formula handling for more flexible inputs.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

- Add promise@^8.3.0 to resolutions to fix Promise.allSettled being undefined on mobile

## Problem

After upgrading React Native from 0.79.5 to 0.81.5, the universal search feature on mobile was stuck in loading state. The root cause was:

1. `fbjs` (dependency of `react-native-web`) requires `promise@^7.1.1`
2. Yarn hoisted `promise@7.3.1` to root `node_modules`
3. `promise@7.x` doesn't have `Promise.allSettled` method
4. When Metro bundler resolved `promise/setimmediate/es6-extensions`, it found the 7.x version instead of 8.x
5. This caused `Promise.allSettled is not a function` error

## Solution

Add `"promise": "^8.3.0"` to resolutions to force all packages to use the same version that includes `Promise.allSettled`.

## Test plan

- [ ] Verify universal search works on mobile (no longer stuck in loading)
- [ ] Verify `node_modules/promise/package.json` shows version 8.3.0 after `yarn install`

### CODE REVIEW

**Comment by revan-zhang** [comment]
### :white_check_mark: **Snyk checks have passed. No issues have been found so far.**

| Status | Scanner |  Critical |  High |  Medium |  Low | Total (0) |
|---|---|---|---|---|---|---|
| :white_check_mark: | Open Source Security| 0 | 0 | 0 | 0 | [ 0 issues](https://app.snyk.io/org/rayston92/pr-checks/0daf58c2-a5b4-4ac1-b129-cbe2369b27d6?refs=dd61be4377069b62908a508525b67770b3cfd398&source=prChecksComment) |
| :white_check_mark: | Licenses| 0 | 0 | 0 | 0 | [ 0 issues](https://app.snyk.io/org/rayston92/pr-checks/0daf58c2-a5b4-4ac1-b129-cbe2369b27d6/license?refs=dd61be4377069b62908a508525b67770b3cfd398&source=prChecksComment) |

:computer: Catch issues earlier using the plugins for [VS Code](https://marketplace.visualstudio.com/items?itemName=snyk-security.snyk-vulnerability-scanner), [JetBrains IDEs](https://plugins.jetbrains.com/plugin/10972-snyk-security), [Visual Studio](https://marketplace.visualstudio.com/items?itemName=snyk-security.snyk-vulnerability-scanner-vs-2022), and [Eclipse](https://marketplace.eclipse.org/content/snyk-security#external-install-button).

**Review by weatherstar — DISMISSED** [review]

**Comment by huhuanming** [comment]
得在这里 packages/shared/src/polyfills/polyfillsPlatform.js 主动注入才行，直接 pkg 里面引用可能会晚了

**Review by originalix — DISMISSED** [review]

**Review by huhuanming — APPROVED** [review]

**Review by weatherstar — APPROVED** [review]
